[Admin] Update CSS nav and drawer
hsipl/order_system pull request #28
Opened 2022-01-03 15:17 UTC by Mei-Yun-W

與這支 PR 有關聯的 OtisPM卡片:

URL: [OtisPM-Project](https://www.otispm.com/otis/index.html#!/pjm/p/8392/backlog?showTodoDetail=133575)

# Description

**Use material-ui to update CSS of navbar, drawer and login page.**

# Step by Step

**Use material-ui to update CSS of navbar, drawer and login page.**

# Screenshot or more (Optional)
**navbar, drawer**
![image](https://user-images.githubusercontent.com/68844503/147946705-fa01fe7c-ad28-4db0-b626-e267471d3c37.png)
![image](https://user-images.githubusercontent.com/68844503/147946764-3d884c09-3ea1-4737-b247-2bc874c5bfd6.png)
**Login page**
![image](https://user-images.githubusercontent.com/68844503/147946795-e24acc3a-eb48-4538-a181-83bf25130730.png)

-----------------

提交 PR 前，請先檢查以下是否已完成：

* [O] 該分支是從最新 `master` 切出來 (如果不是，請先 rebase/merge 它)
* [X] 是否新增測試，或被現有的測試覆蓋
* [O] 這支 PR 是否有明確的標題、內容描述

-----------------

補充說明:
@05050554 @KE-CY  Please reviews this PR

2022-01-03 15:48 UTC, p0937507934 requested changes

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Login.js
> +    console.log(e);
remove all console.log

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Login.js
> +    localStorage.setItem("password", JSON.stringify(password));
save password to localstorage ?  what is this for ?

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Login.js
> +  const handleKeypress = (e) => {
沒看到用在哪

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Navbar.js
> +
這兩個應該可以合起來?

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Navbar.js
> +  const [image, setImage] = useState(null);
State 應該統一放上面

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Order.js
> +const Ordercon = styled(Paper)({
orderCon, OrderCon, ordercon ?

2022-01-03 15:48 UTC, p0937507934 commented on admin/src/components/Order.js
> +  const [lis, setLi] = useState([{ id: 0, content: "" }]);
list ?

2022-01-03 16:01 UTC, aniku777tw commented on admin/src/components/Navbar.js
> +const Topnav = styled(Paper)({
UpperCamelCase
Topnav to TopNav

2022-01-03 16:04 UTC, aniku777tw commented on admin/src/components/Product.js
> +const Productcon = styled(Paper)({
should use the same naming convention

2022-01-04 06:13 UTC, ek2061 commented on admin/src/components/Navbar.js
> +    axios
axios建議寫設定檔或建立新的axios物件避免程式碼過度冗長與重複
```jsx
this.client = axios.create({
  baseURL: process.env.REACT_APP_API_SERVER,
  headers: {
    Authorization: `Bearer ${token}`,
  },
});
```

2022-01-04 07:21 UTC, p0937507934 commented on admin/src/components/Navbar.js
> +    axios
補充一下 
既然友志提到了
很多變數或者固定的東西可以抽出當 const, enum...etc

2022-01-04 07:43 UTC, Mei-Yun-W commented on admin/src/components/Login.js
> +    console.log(e);
已修改

2022-01-04 07:43 UTC, Mei-Yun-W commented on admin/src/components/Navbar.js
> +  const [image, setImage] = useState(null);
已修改

2022-01-04 07:44 UTC, p0937507934 commented
OrderCon, OrderComponent 我不確定你的意思是不是後面這個
如果是的話, 我是覺得有效的命名會好一點
不然看的人都要猜是什麼

axios 的封裝可以之後再補, 目前上線比較急

2022-01-04 07:44 UTC, Mei-Yun-W commented on admin/src/components/Product.js
> +const Productcon = styled(Paper)({
已修改

2022-01-04 07:45 UTC, Mei-Yun-W commented on admin/src/components/Order.js
> +  const [lis, setLi] = useState([{ id: 0, content: "" }]);
之前測試用，已刪除

2022-01-04 07:45 UTC, Mei-Yun-W commented on admin/src/components/Order.js
> +const Ordercon = styled(Paper)({
已修改

2022-01-04 07:46 UTC, Mei-Yun-W commented on admin/src/components/Login.js
> +    localStorage.setItem("password", JSON.stringify(password));
之前測試用，已刪除

2022-01-04 07:53 UTC, Mei-Yun-W commented
https://github.com/Milesfeng/order_system/pull/28#issuecomment-1004588305
已修改

2022-01-04 18:57 UTC, KE-CY commented on admin/src/components/Login.js
> +  const url = "http://140.125.45.154:8000/api/user/login"
154?

2022-01-04 19:33 UTC, KE-CY commented on admin/src/components/Navbar.js
> +          </LeftButton>
LeftButton 或許可以改成 map 來寫 ?

2022-01-05 15:29 UTC, KE-CY commented
請同步最新的 main

2022-01-13 10:32 UTC, Mei-Yun-W commented on admin/src/components/Login.js
> +  const url = "http://140.125.45.154:8000/api/user/login"
已改

2022-01-13 16:27 UTC, KE-CY commented
請同步最新的 main

2022-01-25 09:31 UTC, Mei-Yun-W commented
> 請同步最新的 main
已更新

2022-02-09 09:23 UTC, 05050554 approved these changes
Review, perfect.

2022-02-09 16:36 UTC, KE-CY commented
@p0937507934  CI/CD的錯誤訊息部分目前要先如何處理?

2022-02-10 03:08 UTC, merged